image: docker:latest

variables:
  DOCKER_HOST: "tcp://172.16.0.11:2375"
  APPNAME: "andrewsite"

production:
  type: deploy
  script:
    - docker build -t $APPNAME .
    - docker stop $APPNAME
    - docker rm $APPNAME
    - docker run -d --name $APPNAME -p 5000:5000 $APPNAME
  only:
    - master
