image: docker:latest

variables:
  DOCKER_HOST: "tcp://172.16.0.11:2375"
  APPNAME: "andrewsite"

production:
  type: deploy
  script:
    - apk update
    - apk add ca-certificates wget
    - update-ca-certificates
    - wget -O /hugo.tar.gz http://github.com/gohugoio/hugo/releases/download/v0.22.1/hugo_0.22.1_Linux-64bit.tar.gz
    - tar -xf /hugo.tar.gz -C /
    - /hugo
    - docker build -t $APPNAME .
    - docker stop $APPNAME
    - docker rm $APPNAME
    - docker run -d --name $APPNAME -p 5000:5000 $APPNAME
  only:
    - hugo
