language: node_js
node_js:
<<<<<<< HEAD
  - '4.2.3'

before_script:
  - npm install

script: node node_modules/gulp/bin/gulp
=======
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZXuewXxfFFWDwENLaxQ8pgAYSysuczh4z2fLKcddRBmUMIae2xodTetD2BdR7uufOFg1C3LHiua8DuqsR+OKFTSDdXBCb1RjYxJ4Vao6ehmFZILTWk4ccUzzz99nOEjmyWXhOITIdsAGqdaiklnpheEClpntwQJ2sAxkHtMW/y0=
  app: lobos-personalsite
  on:
    repo: 4ndr3w/PersonalSite
>>>>>>> ae2b91650dabecc0a6905bee6a14203be1cd4cda
