language: node_js
node_js:
  - '4.2.3'

before_script:
  - npm install

script: node node_modules/gulp/bin/gulp

deploy:
  provider: s3
  bucket: andrew.lobos.me
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  local_dir: build
  acl: public_read
  detect_encoding: true
